version: "2"

linters:
  enable:
    - gocyclo
    - staticcheck
    - errcheck
    - govet
    - ineffassign
  settings:
    gocyclo:
      min-complexity: 20
  exclusions:
    rules:
      - text: "is deprecated"
        linters: [all]
