apiVersion: v2
name: kube2iam-chart
# version and appVersion are automatically updated by CI during release
version: 0.0.0
appVersion: 0.0.0
description: Provide IAM credentials to pods based on annotations.
keywords:
- kube2iam
- aws
- iam
- security
home: https://github.com/jtblin/kube2iam
sources:
- https://github.com/jtblin/kube2iam
maintainers:
- name: mariusv
  email: myself@mariusv.com
# The 'engine' field is deprecated in API version v2.
# engine: gotpl