name: Build Image

on:
  push:
    branches:
      - 'master'
    tags:
      - "*"

jobs:
  bake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          buildkitd-flags: --debug
          config-inline: |
            [registry."docker.io"]
              mirrors = ["mirror.gcr.io"]
      - name: Build image
        run: |
          make docker
      - name: Login to DockerHub
        uses: docker/login-action@v1
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Pubish to Dockerhub
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: |
          make release
